// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HeartSpaceAdmin.Models.EFModels;

public partial class EventComment
{
    public int Id { get; set; }

    public int EventId { get; set; }

    public int MemberId { get; set; }

    public string EventCommentContent { get; set; }

    public DateTime CommentTime { get; set; }

    public string Disabled { get; set; }

    public virtual Event Event { get; set; }

    public virtual Member Member { get; set; }
}