// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HeartSpaceAdmin.Models.EFModels;

public partial class Event
{
    public int Id { get; set; }

    public string EventName { get; set; }

    public int MemberId { get; set; }

    public int CategoryId { get; set; }

    public string Description { get; set; }

    public DateTime EventTime { get; set; }

    public string Location { get; set; }

    public bool IsOnline { get; set; }

    public int ParticipantMax { get; set; }

    public int ParticipantMin { get; set; }

    public string Limit { get; set; }

    public DateOnly DeadLine { get; set; }

    public int? CommentCount { get; set; }

    public int? ParticipantNow { get; set; }

    public bool Disabled { get; set; }

    public string EventImg { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<EventComment> EventComments { get; set; } = new List<EventComment>();

    public virtual ICollection<EventMember> EventMembers { get; set; } = new List<EventMember>();
	public virtual Member Organizer { get; set; }

}