// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HeartSpaceAdmin.Models.EFModels;

public partial class Member
{
    public int Id { get; set; }

    public string Account { get; set; }

    public string Name { get; set; }

    public string PasswordHash { get; set; }

    public string Email { get; set; }

    public string ConfirmCode { get; set; }

    public string NickName { get; set; }

    public bool? IsConfirmed { get; set; }

    public bool Disabled { get; set; }

    public string Role { get; set; }

    public int? AbsenceCount { get; set; }

    public string MemberImg { get; set; }

    public virtual ICollection<EventComment> EventComments { get; set; } = new List<EventComment>();

    public virtual ICollection<EventMember> EventMembers { get; set; } = new List<EventMember>();

    public virtual ICollection<PostComment> PostComments { get; set; } = new List<PostComment>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}