// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HeartSpaceAdmin.Models.EFModels;

public partial class PostComment
{
    public int Id { get; set; }

    public int PostId { get; set; }

    public int UserId { get; set; }

    public string Comment { get; set; }

    public DateTime CommentTime { get; set; }

    public bool? Disabled { get; set; }

    public virtual Post Post { get; set; }

    public virtual Member User { get; set; }
}