// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HeartSpaceAdmin.Models.EFModels;

public partial class Post
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public string Title { get; set; }

    public string PostContent { get; set; }

    public DateTime PublishTime { get; set; }

    public int CategoryId { get; set; }

    public int? CommentCount { get; set; }

    public bool Disabled { get; set; }

    public string PostImg { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<PostComment> PostComments { get; set; } = new List<PostComment>();
}