// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HeartSpaceAdmin.Models.EFModels;

public partial class Tag
{
    public int Id { get; set; }

    public string TagName { get; set; }
}